const styles = {
  // --- LAYOUT CHÍNH ---
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    width: '100vw',
    margin: 0,
    padding: 0,
    fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
    overflow: 'hidden',
    backgroundColor: '#f8fafc', // Slate 50
  },
  header: {
    backgroundColor: '#ffffff',
    padding: '12px 40px',
    borderBottom: '1px solid #e2e8f0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.03)',
    position: 'sticky',
    top: 0,
    zIndex: 1000,
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.02)',
  },
  logo: {
    width: '42px',
    height: '42px',
    backgroundColor: '#4f46e5',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    transition: 'transform 0.2s ease',
  },
  headerTitle: {
    fontSize: '22px',
    fontWeight: '800',
    color: '#1e293b',
    margin: 0,
    letterSpacing: '-0.025em',
  },

  // --- NỘI DUNG CHÍNH ---
  content: {
    flex: 1,
    overflowY: 'auto',
    padding: '40px 80px',
    backgroundColor: '#f8fafc',
  },

  // --- SEARCH BAR (Đã đồng bộ User) ---
 searchWrapper: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: '999px',
    padding: '6px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 10px 25px rgba(0, 0, 0, 0.04)',
    transition: 'all 0.3s ease',
  },
  searchBar: {
    flex: 1,
    border: 'none',
    padding: '10px 16px',
    fontSize: '15px',
    outline: 'none',
    color: '#475569',
    backgroundColor: 'transparent',
  },
  searchButton: {
    backgroundColor: '#4f46e5',
    color: 'white',
    border: 'none',
    padding: '12px 28px',
    fontWeight: '600',
    cursor: 'pointer',
    borderRadius: '100px',
    transition: 'all 0.2s ease',
  },

  // --- SKILL SECTION ---
  skillCard: {
    backgroundColor: 'white',
    borderRadius: '24px',
    padding: '32px 24px',
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    border: '2px solid transparent',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  skillIcon: {
    width: '80px',
    height: '80px',
    borderRadius: '24px',
    marginBottom: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'transform 0.3s ease',
  },

  // --- TEST CARDS ---
  testCard: {
    backgroundColor: 'white',
    borderRadius: '20px',
    padding: '24px',
    border: '1px solid #f1f5f9',
    transition: 'all 0.3s ease',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    cursor: 'default',
  },
  tag: {
    padding: '4px 10px',
    borderRadius: '8px',
    fontSize: '10px',
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: '0.025em',
  },

  // --- DROPDOWN MENU ---
  dropdown: {
    position: 'absolute',
    right: 0,
    top: 'calc(100% + 12px)',
    width: '260px',
    backgroundColor: '#ffffff',
    borderRadius: '20px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    border: '1px solid #f1f5f9',
    overflow: 'hidden',
    zIndex: 1001,
  },
  dropdownItem: {
    padding: '12px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    fontSize: '14px',
    color: '#475569',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    fontWeight: '500',
    width: '100%',
    border: 'none',
    backgroundColor: 'transparent',
    textAlign: 'left',
  },

  // --- FOOTER (Đã bổ sung đầy đủ) ---
  footer: {
    backgroundColor: '#ffffff',
    padding: '80px 40px 40px',
    borderTop: '1px solid #f1f5f9',
    marginTop: '60px',
  },
  footerGrid: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr 1fr 1.5fr', // Chia tỉ lệ cột
    gap: '40px',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  footerLogo: {
    fontSize: '24px',
    fontWeight: '800',
    marginBottom: '20px',
    display: 'inline-block',
  },
  footerText: {
    fontSize: '14px',
    color: '#64748b',
    lineHeight: '1.6',
    marginBottom: '24px',
    maxWidth: '300px',
  },
  footerTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: '24px',
  },
  footerLink: {
    display: 'block',
    fontSize: '14px',
    color: '#64748b',
    marginBottom: '12px',
    cursor: 'pointer',
    transition: 'color 0.2s ease',
    fontWeight: '500',
    textDecoration: 'none',
  },

  // --- MODAL & FORM (Cho phần Đăng đề) ---
  modal: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
    padding: '20px',
  },
  modalContent: {
    width: '100%',
    maxWidth: '560px',
    backgroundColor: '#ffffff',
    borderRadius: '24px',
    padding: '32px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  inputField: {
    width: '100%',
    padding: '12px 16px',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    fontSize: '14px',
    outline: 'none',
    transition: 'border-color 0.2s ease',
    marginTop: '8px',
  },

  // --- TABLE NGƯỜI DÙNG (Cho view 'users') ---
  usersTable: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: '20px',
    border: '1px solid #f1f5f9',
    overflow: 'hidden',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.02)',
  },
  tableHeader: {
    display: 'grid',
    gridTemplateColumns: '80px 2fr 3fr 1.5fr 1fr',
    padding: '20px 24px',
    backgroundColor: '#f8fafc',
    borderBottom: '1px solid #f1f5f9',
    fontWeight: '700',
    color: '#475569',
    fontSize: '14px',
  },
  tableRow: {
    display: 'grid',
    gridTemplateColumns: '80px 2fr 3fr 1.5fr 1fr',
    padding: '16px 24px',
    alignItems: 'center',
    borderBottom: '1px solid #f1f5f9',
    fontSize: '14px',
    color: '#1e293b',
    transition: 'background-color 0.2s ease',
  },
  modal: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.75)', // Slate 900 với độ trong suốt
    backdropFilter: 'blur(8px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
    padding: '20px',
    animation: 'fadeIn 0.3s ease-out',
  },
  modalContent: {
    width: '100%',
    maxWidth: '650px',
    backgroundColor: '#ffffff',
    borderRadius: '32px',
    padding: '40px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    maxHeight: '90vh',
    overflowY: 'auto',
    position: 'relative',
  },
  modalTitle: {
    fontSize: '28px',
    fontWeight: '900',
    color: '#1e293b',
    marginBottom: '24px',
    letterSpacing: '-0.025em',
    textAlign: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: '24px',
    right: '24px',
    width: '40px',
    height: '40px',
    borderRadius: '12px',
    border: 'none',
    backgroundColor: '#f1f5f9',
    color: '#64748b',
    fontSize: '24px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
  },

  // --- FORM ELEMENTS ---
  formGroup: {
    marginBottom: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '14px',
    fontWeight: '700',
    color: '#475569',
    marginLeft: '4px',
  },
  inputField: {
    width: '100%',
    padding: '14px 18px',
    borderRadius: '16px',
    border: '2px solid #f1f5f9',
    fontSize: '15px',
    color: '#1e293b',
    outline: 'none',
    transition: 'all 0.2s ease',
    backgroundColor: '#f8fafc',
    fontFamily: 'inherit',
    '&:focus': {
      borderColor: '#4f46e5',
      backgroundColor: '#ffffff',
      boxShadow: '0 0 0 4px rgba(79, 70, 229, 0.1)',
    },
  },

  // --- UPLOAD AREA ---
  uploadArea: {
    border: '2px dashed #e2e8f0',
    borderRadius: '16px',
    padding: '30px',
    textAlign: 'center',
    cursor: 'pointer',
    backgroundColor: '#f8fafc',
    color: '#64748b',
    transition: 'all 0.2s ease',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '12px',
    '&:hover': {
      borderColor: '#4f46e5',
      backgroundColor: '#f5f3ff',
      color: '#4f46e5',
    },
  },

  // --- BUTTONS ---
  modalButtons: {
    display: 'flex',
    gap: '16px',
    marginTop: '32px',
  },
  button: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 20px',
    borderRadius: '10px',
    fontWeight: '600',
    fontSize: '15px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    border: 'none',
  },

  buttonPrimary: {
    backgroundColor: '#4f46e5',
    color: '#ffffff',
    boxShadow: '0 10px 15px -3px rgba(79, 70, 229, 0.3)',
  },
  buttonSecondary: {
    backgroundColor: '#f1f5f9',
    color: '#475569',
  },

  // Style cho danh sách Section đã tạo
  sectionInfoBox: {
    padding: '16px',
    backgroundColor: '#eff6ff',
    borderRadius: '20px',
    marginBottom: '24px',
    fontSize: '13px',
    border: '1px solid #bfdbfe',
    color: '#1e40af',
  },
  testCardHover: {
    transform: 'translateY(-5px)',
    borderColor: '#4f46e5',
    boxShadow: '0 15px 30px rgba(79, 70, 229, 0.1)',
  },
  sectionTitle: {
    fontSize: '24px',
    fontWeight: '800',
    color: '#1e293b',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '32px',
  },
  tagBlue: {
    backgroundColor: '#eff6ff',
    color: '#2563eb',
  },
  tagPurple: {
    backgroundColor: '#faf5ff',
    color: '#9333ea',
  },
  testExam: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    backgroundColor: '#f1f5f9',
    fontFamily: "'Inter', sans-serif",
  },
  examHeader: {
    height: '64px',
    backgroundColor: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 24px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  examTitle: {
    fontSize: '20px',
    fontWeight: '800',
    color: '#1e293b',
  },
  examNav: {
    backgroundColor: '#f8fafc',
    padding: '12px 24px',
    display: 'flex',
    gap: '8px',
    borderBottom: '1px solid #e2e8f0',
    overflowX: 'auto',
  },
  navTab: {
    padding: '8px 16px',
    borderRadius: '8px',
    backgroundColor: '#ffffff',
    color: '#64748b',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    border: '1px solid #e2e8f0',
    whiteSpace: 'nowrap',
    transition: 'all 0.2s',
  },
  navTabActive: {
    backgroundColor: '#eff6ff',
    color: '#2563eb',
    borderColor: '#3b82f6',
    boxShadow: '0 2px 4px rgba(59, 130, 246, 0.1)',
  },
   examContent: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
    padding: '24px',
    gap: '24px',
  },
examLeft: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    padding: '32px',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.05)',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
  },

  examRight: {
    width: '320px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },

  // --- QUESTION CONTENT ---
  questionContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },

  questionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
    borderBottom: '1px solid #f1f5f9',
    paddingBottom: '16px',
  },
  questionType: {
    fontSize: '18px',
    fontWeight: '800',
    color: '#2563eb',
    textTransform: 'uppercase',
  },
 questionText: {
    fontSize: '17px',
    lineHeight: '1.7',
    color: '#334155',
    marginBottom: '24px',
    padding: '20px',
    borderRadius: '12px',
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
  },
  examImage: {
    maxWidth: '100%',
    maxHeight: '380px',
    objectFit: 'contain',
    borderRadius: '12px',
    marginBottom: '24px',
    alignSelf: 'center',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },

  // --- CONTROLS (RECORD & TEXTAREA) ---
  recordButton: {
    display: 'flex',          // Chuyển về flex để căn chỉnh icon và chữ bên trong
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',               // Khoảng cách giữa icon và chữ
    
    // Kích thước ngắn lại
    padding: '10px 24px', 
    width: 'fit-content',     // Nút chỉ dài bằng nội dung bên trong
    minWidth: '160px',        // Đảm bảo nút không quá ngắn khi đổi chữ
    
    // Căn giữa nút
    margin: '20px auto',      // 20px cách trên dưới, 'auto' để căn giữa trái phải
    
    borderRadius: '50px',     // Bo tròn kiểu capsule
    border: 'none',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 12px rgba(239, 68, 68, 0.2)',
    color: '#ffffff',
    textTransform: 'uppercase',
  },
  textarea: {
    width: '100%',
    padding: '20px',
    borderRadius: '12px',
    border: '2px solid #e2e8f0',
    fontSize: '16px',
    fontFamily: 'inherit',
    minHeight: '150px',
    outline: 'none',
    transition: 'border-color 0.2s',
    '&:focus': {
      borderColor: '#3b82f6',
    }
  },
  wordCount: {
    textAlign: 'right',
    fontSize: '13px',
    color: '#64748b',
    marginTop: '8px',
    fontWeight: '500',
  },

  // --- BÊN PHẢI (TIMER & LIST) ---
  timerBox: {
    backgroundColor: '#ffffff',
    padding: '24px',
    borderRadius: '16px',
    textAlign: 'center',
    boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)',
  },
  timerLabel: {
    fontSize: '12px',
    fontWeight: '700',
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '8px',
  },
  timerValue: {
    fontSize: '32px',
    fontWeight: '900',
    color: '#ef4444',
    fontFamily: 'monospace',
  },
  questionsBox: {
    backgroundColor: 'rgb(255, 255, 255)',
    borderRadius: '16px',
    padding: '24px',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05)',
    border: '1px solid #e2e8f0',
    flex: 1,
    overflowY: 'auto',
  },
  questionsTitle: {
    fontSize: '16px',
    fontWeight: '700',
    marginBottom: '16px',
    color: '#1e293b',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  questionGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: '10px',
  },
  questionNumber: {
    aspectRatio: '1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '10px',
    backgroundColor: '#f1f5f9',
    color: '#475569',
    fontSize: '14px',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    border: '2px solid transparent',
  },
  questionNumberActive: {
    backgroundColor: '#2563eb',
    color: '#ffffff',
    boxShadow: '0 4px 10px rgba(37, 99, 235, 0.3)',
    transform: 'scale(1.05)',
  },
  
  // Nút Nộp bài đặc biệt
  buttonPrimary: {
    backgroundColor: '#10b981',
    color: '#ffffff',
    padding: '14px 24px',
    borderRadius: '12px',
    fontWeight: 'bold',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(16, 185, 129, 0.3)',
  },
};

export default styles;